schedules:
- cron: "30 22 * * 2"
  displayName: Nightly Build
  branches:
    include:
      - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/build.yml@eng
  - template: ci/variables/cfs.yml@eng

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    sdl:
      codeql:
        runSourceLanguagesInSourceAnalysis: true

    stages:
    - stage: Build

      jobs:
      - template: /eng/ci/templates/jobs/build.yml@self