
# Action Requires
# 1. Setup the AZURE_CREDENTIALS secrets in your Github Repository by following README.md
# 2. Replace PLEASE_REPLACE_THIS_WITH_YOUR_FUNCTION_APP_NAME with your Azure function app name
# 3. Add this yaml file to your project's .github/workflows/
# 4. Push your local project to your Github Repository

name: Windows_Dotnet_Workflow

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Dotnet 2.2.300
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    - name: 'Run dotnet'
      shell: pwsh
      run: |
        # If your function app project is not located in your repository's root
        # Please change your directory for dotnet build in pushd
        pushd .
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@master
      id: fa
      with:
        app-name: PLEASE_REPLACE_THIS_WITH_YOUR_FUNCTION_APP_NAME
        # If your function app project is not located in your repository's root
        # Please consider prefixing the project path in this package parameter
        package: './output'
    #- name: 'use the published functionapp url in upcoming steps'
    #  run: |
    #    echo "${{ steps.fa.outputs.app-url }}"

# For more information on Github Actions:
#   https://help.github.com/en/categories/automating-your-workflow-with-github-actions
